### ISSUE TITLE
[security] Too permissive permissions set in RteFsUtils functions

### ISSUE THREAD

**Issue by Torbjorn-Svensson** [Open-CMSIS-Pack/devtools#1006]
**Describe the bug**
There are several places in the RteFsUtils class that changes the permission of a resource to 0777.
I assume that the resource should never be world writable etc.

**To Reproduce**
Look int the source code :)

**Expected behavior**
No files should (by default) be world writable. Umask setting should be respected or at least the permissions of the source, in case of a copy/move, should be preserved.

**Environment (please complete the following information):**

- libRteFsUtils
- Version HEAD (main branch)
- OS: all

**Additional context**
N/A

**Comment by JonatanAntoni** [comment]
Addressed by #993

**Comment by Torbjorn-Svensson** [comment]
> Addressed by #993

Not all of them. There are more places where the permissions are changed, but I'm not sure what should be done in those places.

**Comment by JonatanAntoni** [comment]
This is the list of permission changes in RteFsUtils.cpp:
- RteFsUtils::MoveExistingFile
  Might fail if the file to be moved is read-only. Sets the file mode to `0777` after move.
- CopyCheckFile
  Sets the file mode to `0777` after copy.
- RteFsUtils::SetFileReadOnly
  Sets all read-flags, instead of just removing write-flags. Restores file mode to `0777` instead of just restoring required write-flags. This one is addressed by #993.
- RteFsUtils::DeleteTree
  Sets file mode to `0777` before deletion. Ignores directories.
- RteFsUtils::RemoveFile
  Sets file mode to `0777` before deletion.
- RteFsUtils::RemoveDir
  Sets file mode to `0777` before deletion. Is similar to RteFsUtils::DeleteTree

**Comment by jkrech** [comment]
@Torbjorn-Svensson  are you happy that we closing this issue? The fix will be included in the CMSIS-Toolbox 2.0.0.

**Comment by Torbjorn-Svensson** [comment]
> @Torbjorn-Svensson are you happy that we closing this issue? The fix will be included in the CMSIS-Toolbox 2.0.0.

Well no. PR #993 only solves the `SetFileReadOnly` function, not the other functions, so this is not done.

**Comment by jkrech** [comment]
Can you please create a separate Issue to cover this?

**Comment by JonatanAntoni** [comment]
See my last comment. We need to rework all functions in RteFsUtils that change permissions. Ideally, only central functions actually change permissions and all other helper functions eventually use these central functions.

**Comment by jkrech** [comment]
@edriouk can this be closed?
