### ISSUE TITLE
[cbuild] It is unclear what `cbuild --log` does (clarified)

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1042]
I was using this command with `csolution-examples` but did not see any additional log file that is created. 

```
>cbuild Hello.csolution.yml -q -c .Release --log ./out/AVH -r
```

Could someone explain?

**Comment by brondani** [comment]
```
--log arg            Save output messages in a log file
```
You should give the full name for the log file not only the directory, for example:
```
cbuild Hello.csolution.yml -c .Release --log myLog.txt
```

**Comment by soumeh01** [comment]
`--log` option takes the name of the file (with/without extn), provided that the parent path should be existing. If the path doesn't exist or is a path of a directory. `cbuild `throws a **warning** and continue the execution.

```
$ cbuild .Hello.csolution.yml -r --log unknown/test.log
warning cbuild: error creating log file
open unknown/test.log: The system cannot find the path specified.
...
```
or 

```
$ cbuild ./Hello.csolution.yml -r --log ./out/AVH
warning cbuild: error creating log file
open ./out/AVH: is a directory
...
```

In my opinion, The behavior should be in line with the redirect **>** operator. Which redirects all this output to a file and throws an `ERROR` when the path doesn't exist

```
$ cbuild ./Hello.csolution.yml -r > unknown/test_redirect.log
bash: unknown/test_redirect.log: No such file or directory
```
or 

```
$ cbuild ./csolution-examples/Hello/Hello.csolution.yml -r > ./out/AVH
bash: ./out/AVH: Is a directory
```

### Proposal

I would propose to have a behavior the same as the `>` operator.  which is
- Throw `error`  instead of `warning`. When the path doesn't exist or the path specified is the path to a directory.
- Stop the execution when `cbuild` is unable to create a logfile

**Comment by soumeh01** [comment]
@ReinhardKeil @jkrech 
Do you have any comments/feedback/suggestions on the above proposal?

**Comment by jkrech** [comment]
a) throwing an error and stopping the execution is the right approach in case the log file cannot be written (e.g. also due to lack of access permission)
b) why do we implement `--log` if it does exactly the same as redirecting the output using the `>` operator in the first place?
The benefit I was expecting for this dedicated option is that the user does not need to ensure that the directory exists, just like with the `--output` option. I think this would simplify the `scripting` and avoid the user stumbling.

**Comment by soumeh01** [comment]
In reference to the point `b `mentioned, The difference when having `--log` and `>` operator is,

`cbuild ./Hello.csolution.yml -r > test_redirect.log` only captures in the log file (NO logs on STDOUT). If user wants to see the logs on stdout and capture them in the file as well. He/she will have to use different extended command based on the operating system (`tee` or `type` or 'Tee-Object') for e.g.

- In UNIX based bash : `cbuild ./Hello.csolution.yml -r 2>&1 | tee test_redirect.log`
- In Windows cmd or powershell  : `cbuild ./Hello.csolution.yml -r > test_redirect.log 2>&1 & type test_redirect.log`

but with `--log` options, The command is always the same irrespective of the operating system
`cbuild ./Hello.csolution.yml -r --log test.log`
