### ISSUE TITLE
Should we change extension to `*.yaml` of generated files.

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1186]
This is not a bug, but an observation.  https://en.wikipedia.org/wiki/YAML lists as official file extension \*.yaml.

**Question:** _Should we change the extension of the generated files (\*.cbuild\*.yml) to \*.cbuild\*.yaml?_
This would make it more consistent with VS Code plugins (Keil Studio Pack).

**Comment by iomint** [comment]
There are many discussions on internet about yaml vs yml including this one on Stackoverflow : https://stackoverflow.com/questions/21059124/is-it-yaml-or-yml#:~:text=yml%22%20is%20%22the%20file%20extension,and%20is%20much%20more%20common.
One can notice that the recommendation from YAML.org you have pointed above is dated 2006 so quite old and so far .yml is still largely use so to my opinion we can continue to use .yml

**Comment by jkrech** [comment]
Comment from:  [#1177](https://github.com/Open-CMSIS-Pack/devtools/issues/1177)
https://github.com/Open-CMSIS-Pack/devtools/issues/1186 would have some impact on the tools reading the cbuild files, since it is a breaking change. Tools that need to support every version of Toolbox 2.x would need a small amount of additional logic to fall back to e.g. cbuild-set.yml if cbuild-set.yaml could not be found.

**Comment by ReinhardKeil** [comment]
Leaning towards no change, leave the extension `*.yml` as is today.

**Comment by ReinhardKeil** [comment]
Decision: *.yml will be the standard extension used in CMSIS-Toolbox and other Arm products.
