### ISSUE TITLE
When `pack: Arm::CMSIS` instead of `ARM::CMSIS` is used -> warning 500

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1262]
**Describe the bug**

When the case of a pack name is mistyped, i.e. `-pack: Arm::CMSIS` instead of `-pack: ARM::CMSIS` this error is reported.

```
warning csolution: RTE Model reports:
C:/Users/reikei01/AppData/Local/Arm/Packs/Arm/CMSIS/6.0.0/Arm.CMSIS.pdsc: warning #500: pack 'ARM::CMSIS@6.0.0' is already defined in file C:/Users/reikei01/AppData/Local/Arm/Packs/ARM/CMSIS/6.0.0/ARM.CMSIS.pdsc - duplicate is ignored
```

For an user it is unclear that this is caused by the fact that `Arm` instead of `ARM` is used.  The problem is caused by the fact that the `cbuild-pack.yml` file records the pack in upper case from a previous run.

**To Reproduce**
Use attached project DualCore.zip with the command: 
```
csolution convert HelloWorld.csolution.yml
```
[DualCore.zip](https://github.com/Open-CMSIS-Pack/devtools/files/13874117/DualCore.zip)

**Environment (please complete the following information):**

- CMSIS-Toolbox 2.2.1
- OS: Windows

**Comment by jkrech** [comment]
Both HelloWorld_cm4.cproject.yml as well as HelloWorld_cm0plus.cproject.yml specify
```
  packs:
    - pack:  ARM:CMSIS
```
After removing those, the `Arm::CMSIS` pack specifier is accepted and processed as if `ARM::CMSIS` was specified.
Therefore the root cause seems to be a case insensitve comparison when matching the specified packs against the installed packs.

`csolution list packs HelloWorld.csolution.yml` also prints `ARM::CMSIS@6.0.0`.

This is most likely due to using case insensitive Windows OS libraries.

**Comment by jkrech** [comment]
Lower priority than other issues for 2.4.0
