### ISSUE TITLE
[projmgr] list packs related to my project ?

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#127]
When invoking this command:

$ csolution list packs -s projects_layers/R-CUBE.csolution.yml

I get the list of all the packs present in my CMSIS_PACK_ROOT.

I hoped that by providing the csolution I would get the list of packs used by this application.

$ csolution --help
CMSIS Project Manager 0.9.0 (C) 2022 ARM 

Thanks & Regards,
Fred

**Comment by jkrech** [comment]
Fred, once we implement the pack selection and filtering in the csolution and the cdefaults YML files, this will give you the packs visible in the context of the solution.
Isn't the list of used packs more relevant when bound to a project context? In any case the list of used packs is provided in the cprj file after the convert step.
Note that list components also shows the list of available components (filtered e.g. by compiler and device specified by the csolution) rather than the selected components.

**Comment by DavidJurajdaNXP** [comment]
I would expect commands for printing of generic scope information (list packs) in cpackget.
Generic overview might be useful during pack installation as well as during project creation, there is overlap.
Such overlap might be reason for merge of cpackget with csolution into single tool.

**Comment by brondani** [comment]
Agreed. To keep the separation of concerns between Pack and Project Manager, let's change the behaviour of the `csolution list packs` command to list the solution used packs, leaving the generic scope pack listing to `cpackget`.

**Comment by ReinhardKeil** [comment]
In my view this problem is solved by now.

**Comment by jkrech** [comment]
`csolution list packs`   lists all installed packs
`csolution -s <csolution> list packs`  lists all packs specified by the csolution file regardless of context
`csolution -s <csolution> -c <context> list packs` lists all packs specified for the selected context 
The commandline flag `-m` will filter the printed list for packs that are not installed.
This preserves the separation of concerns between `cpackget` and `csolution`. The overlap is the installed pack in the pack root folder and registered local_repository settings.
