### ISSUE TITLE
csolution/convert with attr config : no systematic .base@<version> files in RTE?

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#1472]
Hi

I see some difference in the file management by csolution regarding the attr "config".
Maybe this needs to be more documented?

In my dfp pack, I have:
```
    <component Cclass="Device" Cgroup="Startup" Cversion="0.0.1" condition="STM32U5">
        <file category="source" condition="STM32U575" name="Source/startup_stm32u575xx.c" attr="config" version="0.0.1"/>

```
The csolution convert gives:
```
`-- RTE
    |-- Device
    |   `-- STM32U575ZITxQ
    |       |-- startup_stm32u575xx.c
    |       |-- startup_stm32u575xx.c.base@0.0.1

```
Which is ok for me:
- `Device` is the Cclass
- there is a subdirectory for Dname
- the `.base@<version>` can be useful

We create another pack with:

```
    <component Cclass="Security" Cgroup="stm32_cryptographic" Csub="Crypto interface" Cversion="4.0.1" condition="Crypto Core selected">
        <file category="header" name="include/cmox_default_config.h" version="0.1.0" attr="config"/>

```
The csolution convert gives:
```
`-- RTE
    |-- Security
    |   `-- cmox_default_config.h

```
- `Security` is the Cclass => ok
- no subdirectory in this case => ok but I don't find any documentation for the different cases ?
- no`.base@<version>` => issue ?

Thx

**Comment by jkrech** [comment]
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/build-overview.md#rte-directory-structure
It should depend on the condition, whether or not a sub-directory named after the device is added.
Can you share the component's condition details?

The  PLM of config files is documented here: https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/build-overview.md#plm-of-configuration-files 
and according to that documentation you should see a copy of the configuration file under the name:
`cmox_default_config.h.base@0.1.0`
This looks like a bug.

**Comment by jeromecoutant** [comment]
Thx for the documentation link...

About issue, I can see:
- when cmox_default_config.h is not present before convert, RTE is then created with the file **and** .base copy
- when cmox_default_config.h is already present before convert, RTE doesn't update the file (as expected), but the .base copy is not copied
(for device files, .base files are created in all cases)

**Comment by jkrech** [comment]
Thanks for sharing further analysis.
It makes sense to me that if `cmox_default_config.h` is already present that it is not overwritten and because RTE does not know which version the already present file has, it must not create a `cmox_default_config.h.base@<version>` file using the config file version from the currently selected component version.
In such a situation the user should 
a) create a backup of the `cmox_default_config.h`
b) run the `rte-update` 
c) merge the settings from the backup into the newly copied `cmox_default_config.h`
d) ensure that the `cmox_default_config.h.base@<version>` file is retained / checked-in

I cannot reproduce any different behavior for configuration files for Cclass "Device".

**Comment by jeromecoutant** [comment]
> It makes sense to me that if cmox_default_config.h is already present that it is not overwritten

Yes, this is what is expected.

> it must not create a cmox_default_config.h.base@<version> file using the config file version from the currently selected component version

This is my request...
I expect to rte-update is creating the same base file as the one created if the config file is not available.
Note this is what is done for device config file. Config file from cclass different than device are not managed in the same way than devive cclass files.

**Comment by jkrech** [comment]
@jeromecoutant, which version of the CMSIS-Toolbox are you currently using? I do see differences between version 2.2.1 and 2.3.0.
I think that due to the introduction of the `*.cbuild-pack.yml` the RTE Model considers the component version being "fixed" and therefore it is assumed that a copy of the config file from the pack is the base version of the config file that is present in the RTE directory.
Please validate that CMSIS-Toolbox 2.3.0 is creating the expected results for you.

**Comment by jeromecoutant** [comment]
You're right, I am still using 2.2.1 :-(
I need to check with 2.3.0

**Comment by jeromecoutant** [comment]
Sorry for the noise.... behavior with csolution 2.3.0 is as expected.... 🙄
