### ISSUE TITLE
[csolution] cbuild error on LVGL Pack

### ISSUE THREAD

**Issue by purdurnr** [Open-CMSIS-Pack/devtools#164]
I updated to latest version of tools to get "core0" fix for .cprj output.

- Ran into issue where prior cproject.yml included "board".  New tool excludes board, or fails to find.
- Removing board the resulting project fails to find files for included LVGL pack.  The files can be found in the RTE folder: 
![image](https://user-images.githubusercontent.com/94857467/155802040-d13e87ef-ad99-4af0-9685-a62ef300ed14.png)
 
- The path in error seems in the weeds? 
![image](https://user-images.githubusercontent.com/94857467/155801519-f7180036-261e-4d27-8dfc-0ec77f46144b.png)

Is the issue with the pack being installed prior to update in tool?  I could wipe out and start again with tool/pack/project folders?

**Comment by brondani** [comment]
@purdurnr many thanks for reporting this.
To debug it I would need a reproducer, anyway I could find two issues:
- a regression in the Project Manager concerning the device variant resolution: for multi-variant devices the generic `Dname` was being exported into the generated CPRJ instead of the selected unique variant name.
- an incomplete warning message in the Build Manager: when there are multiple possible variants for a given `Dname`, the Build Manager takes automatically the first variant and prints the warning `M630` where the string `<VAR>` was being printed instead of the variant's name.

Can you please test this devdrop with the fixes?
https://github.com/brondani/devtools/releases/tag/tools%2Ftoolbox%2F0.9.2-dev0

I have also seen that in the pack `NXP::LPCXpresso55S69_BSP 14.0.0` the board `LPCXpresso55S69` has `LPC55S69` as mounted device but according to the [specification](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_boards_pg.html#element_board_mountedDevice) in this case one of the variants should be specified instead.

Thanks
Daniel

**Comment by purdurnr** [comment]
The new devdrop fixed the <VAR> warning.

@brondani you can review the example project here:[https://github.com/purdurnr/lvgl-example](url)

**Comment by brondani** [comment]
@purdurnr thanks for sharing the project.
From your `LVGL.lvgl` pack I see the `lv_conf_cmsis.h` file is declared in this way:
`<file category="preIncludeGlobal" name="lv_conf_cmsis.h" attr="config" version="1.0.0" />`

The Build Manager [evaluates](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/buildmgr/cbuild/src/CbuildModel.cpp#L449-L474) this file as a `Pre_Include_Global.h` as defined in the [specification](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_components_pg.html#Pre_Include_Global_h) instead of evaluating it as a config file with the `preIncludeGlobal` category.

As soon as we have a bugfix I will inform you.

Thanks
Daniel

**Comment by brondani** [comment]
@purdurnr, we have a new CMSIS-Toolbox release, can you please check whether the remaining issue was fixed?
https://github.com/Open-CMSIS-Pack/devtools/releases/tag/tools%2Ftoolbox%2F0.9.2
Thanks
Daniel

**Comment by purdurnr** [comment]
@brondani thanks for helping me get this project working.
That fixed the creation of the valid cprj.  (I also needed to update the file paths that were incorrect)
I was able to build properly.
I just have a cmake install/path issue I need to look into.
Thanks!
