### ISSUE TITLE
[solution] why so many separators in the spec ?

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#165]
Hi,

I agree it is more the spec than the tool but today I need to use many different separators in a project.yml file.
We have ::, :, & and @

[Cvendor::] Cclass [&Cbundle] :Cgroup [:Csub] [&Cvariant] [@[>=]Cversion]

Is it really useful to have so many different separators ?
Is it to be able to deal with optional parts?

Wouldn't it be simpler to say that the separator is always here but only the content can be omitted ?

[Cvendor]:Cclass:[Cbundle]:Cgroup:[Csub]:[Cvariant][@[>=]Cversion]

So, from the more complete: 
    STMicroelectronics:Device:MyBundle:HAL:UART:variant1@>=0.0.1

To the less complete:
    :Device::HAL::@0.0.2

It may look a bit "not so nice" but we do not have to scratch our head to know which separator to choose.

**Comment by fred-r** [comment]
Yes, nothing really serious here.
If this format helps for the parsing, I am fine with it.

**Comment by madchutney** [comment]
Could we eliminate separators entirely from the specification?

Since we are already using a structured data format (YAML), each part of a compound field can be given a dedicated field and documented in the schema.

This would have multiple advantages:
* The available data is more discoverable as there would be an obvious field representing it.
* Some aspects of the description could be moved into the schema e.g. a segment could flagged as `required` or optional in the schema.
* Regular expression can be simplified or eliminated.
* It simplifies in-memory models so that the data needs only to be parsed once (in structured data compound fields require that the data is parsed twice, once to read into memory model and then again whenever the field is read to extract the semantic content).
* Automatic validation tools based on the schema are more likely to detect issues.

**Comment by mark-edgeworth** [comment]
+1 for @madchutney comment here. Please keep each field for a single purpose, with a single piece of data in each.

**Comment by ReinhardKeil** [comment]
>Could we eliminate separators entirely from the specification?
While I understand that this makes data handling in the tools easier, I don't view this a real problem.

We had the request to allow user editable project files and decided to express a component in one line. Today this is working fine, even when I accept some complexity in case of variants and bundles.

I suggest to close this issue.

**Comment by mark-edgeworth** [comment]
Please do not close this just because the current prototype solution seems to work. The solution proposed here is poor and this is probably the one and only opportunity that we have to improve it.
