### ISSUE TITLE
Align `csolution/cbuild` options; potentially add option to generate *.cprj files; hide --cbuildgen from cbuild

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1700]
**The Problem To Be Solved**

Background: The native CMake backend really works great.  Support for legacy cbuildgen can be therefore hidden.

`csolution convert` still generates `*.cprj` files.  Suggest to disable this option to match `cbuild` default.

Maybe there should be an option `--cbuildgen` or a way to create *.cprj files.  For the time being this could be an import into native uVision format.

Should the option `--cbuildgen` and `--cbuild2cmake` be hidden in cbuild.  Is this this even possible?

**Comment by soumeh01** [comment]
My understanding of this enhancement is that the goal is to establish a clear distinction between two workflows (CMake and cprj-based). Essentially, the CMake-based approach will become the default for both tools, while still preserving support for the legacy *.cprj format through cbuildgen.

**Currently**:

`cbuild `has both `--cbuild2cmake`(default) and `--cbuildgen` flags

```
$ cbuild -h
cbuild: Build Invocation 2.5.0 (C) 2024 Arm Ltd. and Contributors

Usage:
  cbuild [command] <name>.csolution.yml [options]

Options:
      --cbuild2cmake       Use build information files with cbuild2cmake backend (default)
      --cbuildgen          Use build information files with cbuildgen backend
```

and csolution convert has default *.cprj generation. Also have an option --cbuild2cmake

```
$ csolution convert -h
csolution: Project Manager 2.5.0 (C) 2024 Arm Ltd. and Contributors

Usage:
  csolution convert <csolution.yml> [OPTION...]

 convert options:
      --cbuild2cmake     Generate build information files only for cbuild2cmake backend
```

I agree with the suggestion to separate the legacy `cbuildgen `functionality to avoid confusion caused by generating irrelevant files. I'd like to propose and summarize the following approach:

- Both `cbuild` and `csolution` should default to the CMake-based approach when no option is specified.
- A single `--cbuildgen` option should be available for both `cbuild` and `csolution` to switch to the legacy cprj-based approach. Note: using `--cbuildgen` should not generate any yml files.

> Should the option `--cbuildgen` and `--cbuild2cmake` be hidden in cbuild. Is this this even possible?

Hiding an option is possible is cbuild. But What is the rationale behind this?

**Comment by ReinhardKeil** [comment]
Thanks for feedback.

I suggest a single control in csolution and cbuild

cbuild help text:
```
      --cbuildgen          Generated legacy *.cprj files and use cbuildgen backend
```

csolution help text:
```
      --cbuildgen          Generated legacy *.cprj files
```

**Comment by soumeh01** [comment]
@ReinhardKeil Thanks for the feedback
@brondani @jkrech 
Do you have any concerns or foresee any potential issues after implementing this change? This update will remove the `--cbuild2cmake` option from both `cbuild` and `csolution`. My only concern is that if some users are currently relying on these flags in their workflows, this could introduce a breaking change for them in the new release.

**Comment by ReinhardKeil** [comment]
I don’t think that this is a serious problem. Please go ahead.
