### ISSUE TITLE
Is version mandatory information in local pack file?

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#253]
Hi

Here is a use case:
I wanted to use a local repo, I then used cpackget to update my local_repository.pidx file.
I can see:
`<pdsc vendor="STMicroelectronics" url="file://localhost/C:/xxx/toggle/" name="Example_HAL_GPIO_Toggle" version="0.0.2"></pdsc>`

0.0.2 is the current version of my local pdsc file.

My question is about csolution and cbuildgen behavior if:
- my project specify this pack with 0.0.3 version?
- I patch my local repo to version 0.0.3 ?

Thx

@fred-r

**Comment by jkrech** [comment]
Each pdsc file regardless whether read from an installed pack or a local_repository only represents a single version.
If I have version 1.0.0 installed and specified as  local pack repository, the installed pack will be ignored and the local repository used. 
You should be able to update the version in the local repository's pdsc file and that version will be looked at ignoring the version at the time of entering it in the local_pack.pidx. So this will also be the version specified in cprj.
Of course you can also decide to restrict the project to use a different version.

**Comment by jkrech** [comment]
When this was designed, the idea was to stick with the existing concept of pidx files we already use for the public packs in ./Web.
In the schema the version attribute is mandatory to provide the information about the latest version.
We thought this would be similarly useful for the local pack, however we found that people will edit the version in the pdsc file without any tool ensuring that the local_repository.pidx would always be updated, similar to nothing forcing a user to download an updated index.pidx file for the public packs.
Since the tools will read the pdsc files of "installed" packs anyhow, the version stored in there will rule, as the user expects.
This is why the version specified in the local_repository.pidx may not be up-to-date. 
I guess any tool listing the local packs (e.g. cpackget), needs to ensure that the file is updated before the information is presented. Removing it would mean to create a separate schema or make the version optional, which I don't think is ideal.
Any suggestions are welcome.

**Comment by jkrech** [comment]
Please note that we have captured this "implementation detail" here: https://github.com/Open-CMSIS-Pack/devtools/wiki/The-CMSIS-PACK-Root-Directory#mandatory-local-repository-packs
