### ISSUE TITLE
Support compiler specific definition

### ISSUE THREAD

**Issue by tcsunhao** [Open-CMSIS-Pack/devtools#277]
For toolchain project, usually macro definitions will be classified into c++, c, asm compiler tags for different compilers to use.
So under project attribute definitions, compiler(c++/c/asm) definitions should be supported.

**Comment by jkrech** [comment]
@tcsunhao please check whether project setups in combination with for-compiler is satisfying your use case?
see: https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-CBuild-Format.md#project-setups
If so, please close the issue, otherwise provide a use case example that is not covered so we can reopen the discussion.

**Comment by tcsunhao** [comment]
Thanks @jkrech, the setup meets NXP needs.
