### ISSUE TITLE
How and where to hook into the build process to run unit tests?

### ISSUE THREAD

**Issue by jankap** [Open-CMSIS-Pack/devtools#342]
I would like to hook into the build process started by `cbuild` to run unit tests in a pipeline. Currently, I use a different, completely independent build tool for that, called [ceedling](http://www.throwtheswitch.org/ceedling). But I'd like to integrate it into the call to `cbuild`.

How would that work? Can I add Cmake lists or should `cbuild` be called by ceedling?

Edit: the unit tests run with GCC and target x86_64 and not ARM to avoid tests on the target or in a emulator. Not sure if that's a good idea at all.

Thanks :)

**Comment by jkrech** [comment]
Sorry for the lack of response, but it looks like we do not have an answer here yet. 
Adding another compiler should be straight forward as you could reuse what is done for GCC and make the necessary deviations e.g. adding a name to the schema (common.schema.json line 55 pattern and adding a dedicated Makefile in the CMSIS_COMPILER_ROOT folder:
etc/GCC-xxx.version.cmake 
But that is only part of your problem as far as I can see.

**Comment by jankap** [comment]
Thank you very much for your  response. 
Is it possible to compile the same cproject with different compilers? 

Is there documentation or are there examples that show how unit testing might work with cbuild?

Thank you!

**Comment by jkrech** [comment]
@jankap we have not been able to make progress here. 
a) we don't have any provisions in the `cbuildgen`'s CMakelist.txt generation to extend/refine it.
b) instead of calling cbuild you should think about your own "orchestration". You should be able to steer output folders and add your own processing in between generating the CMakelist.txt and invoking cmake.
Regarding different compilers, you can specify different compiler e.g. for different build types and depending which build type you select the project will build using the specified compiler toolchain. Today we only officially support AC6, GCC, IAR.

**Comment by ReinhardKeil** [comment]
no further feedback, closing this issue

**Comment by jankap** [comment]
> no further feedback, closing this issue

I'm trying to build my stuff around `cbuildgen`. Is there any documentation, how `cbuildgen` is called from `cbuild`?
