### ISSUE TITLE
Permissive project list for csolution.yml

### ISSUE THREAD

**Issue by slhultgren** [Open-CMSIS-Pack/devtools#376]
It would be very nice if the tooling could allow csolution.yml `project` list to include all projects necessary. (The schema only specifies that the `project` should contain path to the `project file`, format unspecified)

For example it should be possible to link to a `CMakeLists.txt` or `MyCustomProject`.
In this case Open-CMSIS tooling would ignore those unknowns and only care about the files that it recognizes, e.g. `*.cproject.yml`, `*.csolution.yml`, `*.clayer.yml`.

**Comment by ReinhardKeil** [comment]
I think this is covered by https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#prepost-build-steps

**Comment by ReinhardKeil** [comment]
@brondani are the prepost-build-steps already implemented?

**Comment by jkrech** [comment]
@ReinhardKeil , no pre- and post-build steps are not supported yet.

**Comment by brondani** [comment]
From the [#prepost-build-steps](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#prepost-build-steps):

> Tbd: potentially map to CMake add_custom_command.

Since this would require further CPRJ extensions I would rather plan the full CPRJ deprecation and implement the new CMakeLists generation before implementing prepost-build-steps.
