### ISSUE TITLE
Proposal: misc C_CPP instead of C*

### ISSUE THREAD

**Issue by brondani** [Open-CMSIS-Pack/devtools#394]
Some code generators, such as the following Go (golang) code generator from JSON schemas, do not cope with the `*` character because it cannot be used as part of an identifier.
https://github.com/a-h/generate

Would be sensible to use for example the tag `C_CPP` instead of `C*` among the `misc` options?
https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#misc

**Comment by mark-edgeworth** [comment]
Suggest `C-all` or `C-any` perhaps?

**Comment by madchutney** [comment]
Thanks for raising this issue, I suspect that is a fairly common problem and why `Cpp` is commonly used in place of `C++`. 

In this case core issue in the code generation was that characters that are not valid in an identifier name are discarded (not an unreasonable behaviour by the code generator). Therefore `C*` and `C` become synonymous and result in incorrect serialisation.

In other places where "invalid" characters are used they do not contribute to the unique name so when they are discarded there has been no ill effect. For example `not-for-type` can be mapped to `NotForType` without a clash with any other field name.

The safest separator is normally underscore `_`, but since hyphens `-` are already used, I would prefer consistency.

In terms of a name, I'll throw `C-common` into the mix, but happy with any of the suggestions `C-CPP`, `C-all` or `C-any`.

**Comment by ReinhardKeil** [comment]
I suggest to use `C_CPP` as it makes it clearer that it is for both, C and CPP.

**Comment by brondani** [comment]
`C-CPP` is being introduced in the latest [CMSIS-Toolbox](https://github.com/Open-CMSIS-Pack/devtools/releases/tag/tools%2Ftoolbox%2F1.0.0).
`C*` remains temporary present but is deprecated and will be removed in future releases.
