### ISSUE TITLE
Limit csolution memory usage when no pack filter is specified

### ISSUE THREAD

**Issue by mcgordonite** [Open-CMSIS-Pack/devtools#412]
There is a danger that `csolution convert` can consume a lot of memory when no pack filter is specified in the csolution.yml. In this case, `csolution` loads all installed packs. This can result in out-of-memory errors in cloud services or CI flows, particularly where there are a lot of installed packs.

It is important to add some protection to the csolution executable that avoids this situation if a list of packs and/or pack filter is not specified. This should be implemented inside csolution to avoid external systems making assumptions about internal limitations. However, it will most likely have to be an optional check as csolution also has a desktop use case where only a small subset of packs will be installed.

**Comment by brondani** [comment]
On this matter I would propose the following changes for solutions **without** explicit required packs:
1 - By default load only the latest packs
2 - Add a command line option to load all installed packs (`-a`, `--all`)
3 - Add a command line option to accept only solutions with required packs (`-r`, `--required`)

**Comment by mcgordonite** [comment]
Thanks @brondani, that proposal looks good to me. Would `-r` result in csolution exiting with a non-zero exit code when asked to load a csolution with no packs?

**Comment by ReinhardKeil** [comment]
I suggest to only load latest packs by default.  If someone wants a specific pack versions, this could be explicitly requested using the `pack:` node with version information.

**Comment by brondani** [comment]
@mcgordonite In the PR https://github.com/Open-CMSIS-Pack/devtools/pull/495 the following option was added:
```
-l, --load arg        Set policy for packs loading [latest|all|required]
```
For your use case it means when using `--load required` only the packs listed under the `packs` node in csolution.yml will be loaded and csolution will return a non-zero exit code when asked to load a csolution.yml with no packs.
It will appear in the next CMSIS-Toolbox release.

If the option `--load` is not set, the new default behaviour is to load the latest packs instead of loading all installed packs. This saves memory and improves loading time.  

@ReinhardKeil the pack notation with vendor only e.g. `- pack: ARM` for loading vendor specific packs is already accepted in the current release.

**Comment by brondani** [comment]
@mcgordonite Can you please check whether the option `--load required` introduced in csolution [1.2.0](https://github.com/Open-CMSIS-Pack/devtools/releases/tag/tools%2Fprojmgr%2F1.2.0) works as you expect? Thanks

**Comment by mcgordonite** [comment]
Closing this issue: I've tested this out and `--load required` satisfies our use case.
