### ISSUE TITLE
Document how a compiler can be added to CMSIS-Toolbox

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#493]
There should be documentation on how a new compiler can be added to the CMSIS-Toolbox.

See also previous issue #120

**Comment by jkrech** [comment]
a) define a `compiler_name` for the new compiler
b) add this `compiler_name` to the `"CompilerType":` in the schema file: https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/schemas/common.schema.json 
c) create a copy of an existing compiler cmake file (`compiler_name.<version>.cmake e.g. GCC.11.2.1.cmake here:
https://github.com/Open-CMSIS-Pack/devtools/tree/main/tools/buildmgr/cbuildgen/config
and store as `compiler_name.<version>.cmake`
d) edit the file to map the symbols

- executable names: AS, CC, CXX, OC
- processor: CPU = Cortex-M*, SC[13]00,
- fpu code generation: FPU = SP_FPU, DP_FPU, 
- ...
- CMAKE_C_COMPILER_ID/VERSION/...

@brondani what am I missing before we add this to the documentation?

**Comment by ReinhardKeil** [comment]
Note: This is not an urgent request.  We can first complete the infra-structure (i.e. complete compiler agnostic controls).

**Comment by brondani** [comment]
@jkrech We should document the purposes of variables and functions in the toolchain specialized *.cmake file:

| CMake variable               | Description |
| ---------------------------- | ----------- |
| ASM_CPU, CC_CPU and CXX_CPU | device selection set according to the combination of device attributes (CPU, FPU, DSP, MVE, etc.) |
| AS_LEG_CPU, AS_ARM_CPU, AS_GNU_CPU | similar to the previous item but for assembly dialect variants (if applicable) |
| ASM_FLAGS, CC_FLAGS, CXX_FLAGS, LD_FLAGS | flags applicable to all modules of the given language |
| CC_SECURE, LD_FLAGS, LD_SECURE | flags applicable only for secure projects |
| _PI | preinclude option |
| _ISYS | system include option |
| LIB_PREFIX | generated library name prefix |
| LIB_SUFFIX | generated library name suffix |
| EXE_SUFFIX | generated executable name suffix |
| ELF2HEX | flags for ELF to HEX conversion |
| ELF2BIN | flags for ELF to BIN conversion |
| CMAKE_C_COMPILER_ID | CMake compiler identifier |
| CMAKE_C_COMPILER_VERSION | CMake compiler version |

**function(cbuild_set_defines lang defines)**
| Variable               | Description |
| ---------------------- | ----------- |
| lang | language |
| defines | list of generic defines to be replaced by toolchain specific formatted defines |

**function(cbuild_set_options_flags lang optimize debug warnings flags)**
| Variable               | Description |
| ---------------------- | ----------- |
| lang | language |
| optimize | generic optimize selection |
| debug | generic debug selection |
| warnings | generic warnings selection |
| flags | list of toolchain specific formatted flags |

**Comment by VGRSTM** [comment]
@brondani +2 solving https://github.com/Open-CMSIS-Pack/devtools/issues/367

**Comment by ReinhardKeil** [comment]
Now documented here https://github.com/ReinhardKeil/devtools/blob/main/tools/projmgr/docs/Manual/Build-Operation.md

@brondani could you review for completeness?

**Comment by brondani** [comment]
@ReinhardKeil I believe we should make a better distinction between the device features (device attributes in PDSC) and the user selection that leads to compiler options (device attributes in CPRJ). For this reason I would propose to write out the possible values directly in the [cmake-variables table](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Build-Operation.md#cmake-variables) instead of linking the enums from the PDSC.

For example the branch protection possible values make evident the difference: instead of the [`DpacbtiEnum`](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#DpacbtiEnum) from PDSC, the [`DbranchProtEnum`](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/buildmgr/cbuildgen/config/CPRJ.xsd#L165-L172) values from CPRJ should be listed:

| CMake variable     | Description            |
| ------------------ | -----------------------|
| `NO_BRANCHPROT`   | Not Used               |
| `BTI`             | BTI (Branch Target ID) |
| `BTI_SIGNRET`     | BTI + Sign Return      |

To have the full picture maybe we could also extend the table with the possible input YAML values.

In addition to the variables, the functions `cbuild_set_defines` and `cbuild_set_options_flags` should be documented.
