### ISSUE TITLE
Issues with `output-dirs:`

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#557]
This are some observations for the `output-dirs:` option.  

**Proposal:**  Rename `output-dirs:` to just `output:` as this section might be extended to control also the cmake target name.

**Bug:** `output-dirs:` seems only to work at the level of the `*.csolution.yml` file.  Additing `output-dirs:` to a `*.cproject.yml` seems to be ignored.  Is this intentional?  Also the directory settings in `*.cproject.yml` should be relative to the `*.cproject.yml` file.

Reproducer "Demo.2.zip".  Steps to reproduce:
```
./Demo2>csolution convert -s Demo.csolution.yml
./Demo2>cbuild "..\Demo\AWS_MQTT_MutualAuth_SW_Framework\Demo.Release+AVH.cprj"
```
[Demo2.zip](https://github.com/Open-CMSIS-Pack/devtools/files/9869553/Demo2.zip)

**Review:**
Currently the `csolution` tool creates the `*.cprj` file in the directory structure of the project itself.  IMHO this is OK,
But, the default build output directory is relative to the `*.csolution.yml` file. IMHO, by default, each project should have output directories that are relative to the `*.cproject.yml` file.

**Comment by brondani** [comment]
@ReinhardKeil As mentioned [here](https://github.com/Open-CMSIS-Pack/devtools/issues/314#issuecomment-1174862661) the `output-dirs` are initially accepted only at csolution level.
Extending it to cproject (and to clayer?) (and to component?) brings other questions:
- Which child nodes should be accepted at each level?
- What is the behaviour when multiple values are set? Never allowed, only allowed if equivalent, allowed following a priority order and throw a warning or silently process further?

**Comment by ReinhardKeil** [comment]
>Which child nodes should be accepted at each level?

Do you see any problems?  #558 is my proposal for default settings.  Not sure if this causes issues during implementation.

>What is the behaviour when multiple values are set? Never allowed, only allowed if equivalent, allowed following a priority order and throw a warning or silently process further?

`cproject.yml` settings overwrite the settings of `csolution.yml`

**Comment by brondani** [comment]
I see many open questions because there is no intuitive logical behaviour.
The default value for `rte-dir` at project level is `<cproject.yml base directory>/RTE` and for config files of components belonging to layers the default is `<clayer.yml base directory>/RTE`.
When customizing the `rte-dir`, should all config files be written in such directory or those relative to layers should be handled differently?
Should `rte-dir` be accepted in clayer? or even at component level?
Does `rte-dir` being in csolution.yml, cproject.yml or clayer.yml play a role?
Should other custom folders be accepted in clayer?
What would be the overwriting/inheritance behaviour in such case?

**Comment by brondani** [comment]
Another question: if accepting the customization at component/class level, should the board/device specific subfolder be preserved or overwritten (as it seems to be requested in https://github.com/Open-CMSIS-Pack/devtools/issues/410)?

**Comment by ReinhardKeil** [comment]
I believe the remaining issue is covered here #898 
Hence I'm closing this.
