### ISSUE TITLE
cproject/clayer: Add component property to cause component files to be copied into the project tree

### ISSUE THREAD

**Issue by KarolSaja-AlifSemi** [Open-CMSIS-Pack/devtools#658]
Currently csolution/cbuild reference components from a local pack repository under %CMSIS_PACK_ROOT%. This proves problematic when modifications are needed to any of these files (e.g. when extending a driver or instrumenting it for debug), as it will affect every project using these components in that repository. Additional property specifiable for "component" objects in cproject/clayer files could be provided for csolution to extract the components into the project tree instead. In a way, this behavior would be somewhat similar to "config" attribute in PDSC, except it'd be defined by the project developer, not by CMSIS pack creator.

The workaround for this currently is to manually copy the sources into the project and specify them individually under "files".

**Comment by jkrech** [comment]
Hi @KarolSaja-AlifSemi, thanks for sharing your concern.
Conceptually the introduction of packs and components is to share and reuse code as "read-only" with the exception of configuration. Once you start modifying the source code of components developed and maintained by other people you are on your own somewhat defeating the purpose of "not having/wanting to worry about this piece of your software stack".
There is a bit more flexibility in csolution already:
a) you can also copy the pack content into your project/workspace and reference it "locally" by providing the relative `path` to a pack.
https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#pack

b) alternatively you can specify an alternative location for a pack version being used by all projects using `cpackget add path/to/Vendor.PackName.pdsc` 
https://github.com/Open-CMSIS-Pack/cpackget#adding-packs
This is intended as a temporary measure until your changes become part of an official release.
Because ideally you provide feedback to the pack vendor with the changes and extensions you require. Especially for packs maintained in a public repository, modifying individual files while maintaining the overall pack structure will allow people to contribute via Pull Requests and the whole ecosystem of users benefits.

I hope this explains the approach.

**Comment by ReinhardKeil** [comment]
Solved by https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/build-overview.md#source-code-of-software-packs
