### ISSUE TITLE
[csolution] package requirements info are not taken into account?

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#659]
Hi

In some packs, we have:

```
  <requirements>
    <packages>
      <package vendor="STMicroelectronics" name="aaa" version="X.Y.Z"/>
    </packages>
  </requirements>
```

It seems that csolution convert procedure doesn't check this part ?
I can set any lines, there is no check with the packs indicated in the csolution file.

Regards,

**Comment by jkrech** [comment]
@jeromecoutant: Thanks for raising this. I think we need to review this feature. In the csolution.yml we today specify the required packs but do not rely on the requirements for other pack versions provided in the pdsc files to complement that list.
Instead these package level requirements are today considered by the PackManager implementation in MDK and Eclipse. The package managers display an `Install +` instead of `Install` if there is other requirement for other packs. If the required pack is missing this will be shown in the output window and in the GUI there is a button `Resolve`. 
`cpackget` does not implement this feature today.
In my view `cpackget` is the tool that should be concerned about this rather than `csolution`.

**Note**: once `csolution` starts using the `*.cbuild.yml` files as "additional input" all used pack versions are known even in case the csolution.yml files do not list any packs or just packs with wildcards.

**Comment by fred-r** [comment]
I think the point from @jeromecoutant is that:
- ok, cpackget is in charge of installing the packs and may check the depenencies
but
- in csolution.yml we can specify the list of packs and this takes precedence over CMSIS_PACK_ROOT (only these packs are considered)

So, if csolution.yml defines the list of packs to be used, then probably csolution should check the dependencies to lake sure we have all required packs?

Thanks & Regards,
Fred

**Comment by jeromecoutant** [comment]
> if csolution.yml defines the list of packs to be used, then probably csolution should check the dependencies to make sure we have all required packs?

That is what I thought : required packs with the minimal version 
Thx

**Comment by jkrech** [comment]
Thanks for clarifying. Is this a priority for cmsis-toolbox 2.0. Is anyone volunteering for adding this check?

**Comment by edriouk** [comment]
implementd by PR  https://github.com/Open-CMSIS-Pack/devtools/pull/1105
