### ISSUE TITLE
use multifile file compilation with IAR

### ISSUE THREAD

**Issue by tarek-bochkati** [Open-CMSIS-Pack/devtools#685]
IAR compiler provides `--mfc` option which:
> This means that the compiler compiles
> one or several source files specified on the command line as one unit, which makes
> interprocedural optimizations such as inlining, cross call, and cross jump possible
>
> **Example**: iccr32c myfile1.c myfile2.c myfile3.c --mfc

Is it possible to instruct cmake to compile source files in one shot like the example above.

**Comment by tarek-bochkati** [comment]
cc: @mario-pi

**Comment by mario-pi** [comment]
@tarek-bochkati thanks for reporting this. Is this something which is already supported by CMake / cbuildgen for GCC?

**Comment by tarek-bochkati** [comment]
> @tarek-bochkati thanks for reporting this. Is this something which is already supported by CMake / cbuildgen for GCC?

I not aware if this is available for gcc neither for AC6
But this is a nice alternative for LTO.
So it would be nice if we can do this using the generated CMakeLists.txt

**Comment by ReinhardKeil** [comment]
This is something for @mario-pi to investigate.

**Comment by mario-pi** [comment]
@tarek-bochkati  is this something that can be of interest for other CMSIS Toolbox toolchains? Would we then need some generic project attribute to mark that a specific group of files in the project should be compiled together if possible?

**Comment by tarek-bochkati** [comment]
@mario-pi , sure every toolchain should be able to compile a set of files together,
but I'm not sure if other toolchains than IAR are able starting from multiple source files to generate another object file.

today, GCC/CLANG/AC6 using just `-flto` for each file then for the link stage we are able to get great size and speed optimizations.

the fact that IAR needs to compile all the files in the same command using `-mfc --discard_unused_publics` to enhance the footprint is a bit incompatible with current CMake behavior in CMSIS-toolbox.

My request is to check of CMake could be instructed in some way to do this one shot compilation.
and if possible how we could adapt the toolbox to be compatible with this IAR feature.

**Comment by jkrech** [comment]
@brondani, do we have provisions in cbuildgen today to instruction CMake to build multiple source modules with the same invokation of the compiler? Pre-requisite of that would be that the command line options match for all listed modules.

**Comment by brondani** [comment]
`cbuildgen` creates CMakeLists specifying the source modules inside standard CMake functions [`add_executable`](https://cmake.org/cmake/help/git-master/command/add_executable.html) or [`add_library`](https://cmake.org/cmake/help/latest/command/add_library.html), so all modules are part of a given CMake target, there is no special grouping. Of course each module has its own properties which can match or not.
In my opinion no change in this behaviour is required because a proper implementation of the IAR `--mfc` option in the CMake upstream would take in consideration the fact modules with mismatching compile options cannot be compiled in the same call.
@mario-pi @jlonnberg Please advise whether there is any planned contribution to CMake concerning the multi-file compilation support.

**Comment by massonal** [comment]
CMake targets have a property [UNITY_BUILD](https://cmake.org/cmake/help/latest/prop_tgt/UNITY_BUILD.html#prop_tgt:UNITY_BUILD) which allows doing batch compilation. The behavior can be tuned using various other properties.

The docs recommend setting UNITY_BUILD as an environment variable to let users easily turn it on or off. So I think no specific support is needed in the CMakeLists.txt files we generate.

**Comment by brondani** [comment]
@massonal Thanks for the hint. Unfortunately it seems UNITY_BUILD does not enable the multi-file compilation as required in this GH issue. It actually creates a file (e.g. `unity_0_c.c`) where the source modules are included. A bad side effect is the generation of the compilation database (compile_commands.json) with such unity file instead of the original sources.

**Comment by massonal** [comment]
Oh ok, I get the issue then.

In this case, if you really need the 1:1 compilation database, I don't see how CMake could support building multiple files at once, because it would imply "fresh build" and "incremental build" commands are separate. When only a few files are outdated, only the relevant sources are re-compiled, so you can't have a command in compile_commands.json that describe all cases.

**Comment by jkrech** [comment]
After reviewing with IAR we decided to close this issue.
a) we currently don't see a way how cmake would be able to group modules with common command line options.
b) compilation times would increase for modules that are built together as no incremental builds are possible
c) the overall optimization (benefit) may not be very significant
