### ISSUE TITLE
Global defines and file specific defines

### ISSUE THREAD

**Issue by jlonnberg** [Open-CMSIS-Pack/devtools#733]
Problem shown by trying to port the GCC Asm test project to use IAR Toolchain.

The GCC Asm Target.cproj included in the test-suite lists that same defines both on a global level and for specific asm-files. Running the cmake generation script will with the current design add both global defines and file-local defines to the command line resulting in compilation errors with the IAR Assembler as it does not allow listing the same define twice.

How should one go about this? As I see it there are three ways:
1. Modify the IAR toolchain file to filter out any defines that is being re-added.
2. Enforce the writer of the cproj fileto not pass defines that are added on a global level on file-specific levels as well.
3. Have the define-system as overrides, meaning that a file with local overrides does not use the global defines.

Personally, I leaning towards number 2. @brondani @JonatanAntoni opinions on this?

**Comment by ReinhardKeil** [comment]
This is a know problem (see #607).  We will first solve it by applying `define:` and `add-path:` only to C and C++ source files.

**Comment by jkrech** [comment]
The problem here is the hierarchical processing even if settings are only applied to a single language type. A define that is specified on a global level maybe duplicated by a define on the file level. The tool may not allow to specify the same define twice on the command line.
@brondani does csolution have the ability to 
a) identify duplicate defines
b) remove duplicates when generating `cprj`

**Comment by jkrech** [comment]
CMSIS-Toolbox 1.5.0
