### ISSUE TITLE
csolution does not use 'isDefaultVariant' of a component

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#740]
https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_components_pg.html#element_component
specifies a default variant (with 'isDefaultVariant' attribute) of a component, but `csolution` does not use this attribute as it would be otherwise **impossible to specify a component that has an empty "Cvariant" string**.

The current documentation https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#component-name-conventions for "Partly defined components" is therefore incorrect.

Potential Mitigation:
  - (a) clarify in PDSC specification that 'isDefaultVariant' must not refer to a `Cvariant` with a non-empty string when other components with an empty `Cvariant` string are defined.
  - (b) extend PackChk to check for such scenarios.
  - (c) check existing packs for situations defined under (a)
  - (d) extend `csolution` to support `Cvariant`, but change the algorithm that newer versions take precedence.

Is this acceptable?

**Background**

Typical use case of 'isDefaultVariant' is to support evolving components.  For example.

Pack Version 1:  defines just one component, i.e. `CMSIS:RTOS:FreeRTOS`  (hence no `Cvariant` exist).

Pack Version 2: extends this component with variants, i.e. `CMSIS:RTOS:FreeRTOS&Debug` and `CMSIS:RTOS:FreeRTOS&Release`,   `isDefaultVariant` is set for `&Release` (this was also the behaviour of the component in Pack Version 1).   

It is therefore desired to extend csolution with support for `isDefaultVariant` as it better allows to migrate to newer software packs.

>**Note:** It would be still possible to define `CMSIS:RTOS:FreeRTOS` with `isDefaultVariant` set, but it should be an error if this `Cvariant` still exist in parallel.

**Comment by jkrech** [comment]
The basic rule of partially specified component resolution is that it only succeeds, if there is only a single match. In case the partially specified component does not specify a version, the single match is required for componentIDs without considering the `Cversion` and the componentID with the highest `Cversion` gets selected. In any other case the partial component ID requires refinement by the user in the project description.
(**Note:** It is understood that the outcome of the resolution depends on the set of components that are provided by the selected pack versions.)

The attribute `isDefaultVariant="true"` is only considered in case the component resolution results in a list of componentIDs with Cvariant specified. If and only if there is only a single componentID with the `isDefaultVariant="true"` (potentially without considering `Cversion`), this component will get selected just as if there has been a single match only. Otherwise the user is required to refine the componentID in the project.
(**Note:** An algorithm for automatic component dependency resolution should probably not rely on  the `isDefaultVariant="true"` attribute to select a component variant, but instead ask the user to decide.)

(**Note:** A tool displaying available components shall not make any assumptions about a `isDefaultVariant="true"` being a `preferred` component.)

`packchk` should warn if in the scope of validated packs there is common componentIDs with and without `Cvariant`, where `isDefaultVariant="true"` is set, because the componentID without `Cvariant` would always become selected then.

**Comment by ReinhardKeil** [comment]
An alternative that avoids the complexity listed in the beginning of this issue is:

Allow to express and empty `Cvariant` string by extending the [component naming conventions(https://github.com/ReinhardKeil/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#component-name-conventions) with:
```
 component: ARM::CMSIS:RTOS2:Keil RTX5&
```
Just `&` would denote that the `Cvariant` string is empty.

**Comment by jkrech** [comment]
to be released in cmsis-toolbox 2.0.0-dev3
