### ISSUE TITLE
Use local version of cbuild during tests

### ISSUE THREAD

**Issue by jlonnberg** [Open-CMSIS-Pack/devtools#750]
When running integration tests, a version of cbuild is downloaded from an official repo.

Why not build and use a local version in the tests? It seems kind of counter-productive to have work with local changes but still download a pre-build binary as it limits my flexibility and increases the complexity of the test-suite.

**Comment by jkrech** [comment]
Just to be clear `cbuild` is maintained in a separate repository https://github.com/Open-CMSIS-Pack/cbuild/ and therefore the automated tests refer to a previously released version. Maybe we need some way to override this when running these tests locally.

**Comment by jlonnberg** [comment]
@soumeh01 So, it's not a restriction on testing the local changes but I would say it has a negative effects on readability and complexity. So if I would statue my use case:
"As a developer, I wan't to easiliy reproduce the outcome of a integration test"
The current tests runs a binary that only exists during the test-execution instead of genereting a command line for cbuildgen+cmake which I can copy to directly.

**Comment by brondani** [comment]
@jlonnberg Thanks for raising this issue.
I believe there is room for improvement and we should think about the best environment setup we could have without degradation of tests coverage, both locally and when running on CI.
Currently every tool is released separately, for this reason also the binaries of dependent tools are downloaded from their releases instead of building them locally.
We could think about setting up the development environment having `cbuild` or `cmsis-toolbox` as the entry point and add the dependent tools as submodules. The integration tests could be moved to the top level repo. Ideally this approach should be kept in sync with the idea of having individual releases as well, for example by using tagged submodules instead of just checking-out the main branches heads. Also the full integration tests should run for every relevant tool.
Ideas, alternatives, best practices recommendations are welcomed!

**Comment by jlonnberg** [comment]
@brondani I have not embraced the cbuild repo in depth yet but some ideas from my side would be:
- The integration tests in devtools run the tests using cbuildgen+cmake which are the active components that are needed for the test-suite.
- If cbuild is just a wrapper for the other tools, why not write a testsuit for cbuild that checks that it generates correct commandlines for the underlying tools? This gives a clear separation between the repos but will perhaps trigger compatibility issues.

**Comment by ReinhardKeil** [comment]
@jlonnberg can this be closed or are there still issues with it?

**Comment by jlonnberg** [comment]
@ReinhardKeil From what I know, nothing has been done to change the current behaviour. This is a design-question and I believe that the current test-system can be improved and easier to use. I believe that binaries are still downloaded based on stale versions  of cbuild when testing as well as larger parts of the tests are enclosed in shell scripts forcing the usage of bash on windows instead of opting for a more flexibile launguage, e.g., python.

**Comment by ReinhardKeil** [comment]
While the test system might be not easy to use, lets decide if it would be worth investing.  Why should the test system improve? How would be the more flexible way look like? When and why this is needed? What is the effort?

**Comment by ReinhardKeil** [comment]
This is now covered in https://github.com/Open-CMSIS-Pack/devtools/issues/1508
