### ISSUE TITLE
Reproduce input parameters of `cbuildgen` to create CMakeLists.txt

### ISSUE THREAD

**Issue by jankap** [Open-CMSIS-Pack/devtools#793]
In order to split the process of `CMakeLists.txt` file creation and the actual build, I'm trying to hook into `cbuild` and `cbuildgen`.

[Here](https://github.com/Open-CMSIS-Pack/devtools/tree/main/tools/buildmgr) is stated that

> cbuild replicates the steps of pack-aware IDEs with the following build flow:

>
> Call cbuildgen to generate a packlist with URLs of missing software packs. If packs are missing:
> Call [cpackget](https://github.com/Open-CMSIS-Pack/devtools/blob/main/cpackget) to download and install missing software packs.
> Call cbuildgen to generate a CMakeLists.txt file.
> Call [CMake](https://cmake.org/documentation/) to compile the project source code into the binary image using the specified CMake generator.

So, I thought to reproduce the call to `cbuildgen`, just to create the `CMakeLists.txt` files which are needed by some linting tools. I don't need the whole build in that case.

An additional application would be the VSCode cmake-tools extension to quickly change build targets without lots of copy & paste.

What exactly does `cbuild` to? In the code I see that it modifies (creates?) RTE folders, but I can't find the place where `cbuildgen` or any other class methods from the folder are called. 

Can you describe how the process works?

Thanks!

**Comment by jkrech** [comment]
```
cbuildgen <context>.cprj cmake
``` 
should just generate the CMakeLists.txt which I think is what you are asking for.
The RTE update (generating the RTE_Components.h) should only be invoked if you call `--update-rte`.
What are you seeing? 

In early versions of the tools we actually used a shell script rather than a go application.
https://github.com/Open-CMSIS-Pack/devtools/releases/download/tools%2Fbuildmgr%2F0.10.5/cbuild_install.sh
after installation you will find the `cbuild.sh` in the `bin` folder.
Maybe that helps?

**Comment by jkrech** [comment]
@jankap was the above information useful?

**Comment by jankap** [comment]
> @jankap was the above information useful?

Yes, it works, thank you.
