### ISSUE TITLE
 [projmgr] Get rid of project name usage as much as possible

### ISSUE THREAD

**Issue by VGRSTM** [Open-CMSIS-Pack/devtools#81]
I would push to not propagate project name across project description files, artifacts, etc.
From my experience it's a real pain thinking alive project having at a point end user expecting to rename a project. Project renaming is so common / one click operation if IDE usage. Promoting project name at too many places is a mess then including source control workflow pain.

Current project manager proposal is requiring from my trial to get a unique name if *.cproject files. Most obvious policy is \<project name\>.cproject.yml. By the end of process lot of artifacts are project name related like:
  -  \<project name\>.cprj
  -  \<cprj\>\<target\>\<output intdir="\<project name\>_IntDir" outdir="\<project name\>_OutDir"\>\</target\>\</cprj\>

I would push to get rid as much as possible of project name propagation. Thinking best is to rely on directory structure which is required anyway to support data separation. I would prefer to move:
- from \<project name\>.csolution.yml to .csolution.yml
- from \<project name\>.cproject.yml to .cproject.yml
- etc. ...
- from \<output intdir="\<project name\>_IntDir" to \<output intdir="IntDir"

Please find attached some basic project setup allowing to support PR contribution activity: [GetRidOfProjectName.zip](https://github.com/Open-CMSIS-Pack/devtools/files/7911252/GetRidOfProjectName.zip) 
Extra note: as part of such delivery "*_OK" material is tagged as "OK" because only functional setup if current project manager code base ... per my comment I would push to get "*_KO" material being supported as result of such issue solving

**Comment by ReinhardKeil** [comment]
Vincent, could you please explain this in today's meeting.

**Comment by jkrech** [comment]
I have not seen the conclusion yet that we have agreed on a single solution file per directory, so in theory the above proposal would mean <anything>.csolution.yaml contains an entry specifying the ```name``` of the solution. Also I guess the same principal would be applied to clayers as well.

How do we reference projects/layers going forward. Are we specifying the "name" the filename or both? If we use only the name this means the tool reads all cproject.yml files in the directory structure and find out the name. But this means that a user at a file level has to open a file in order to find out the name of the project.

I guess I am really "old school" but what is so bad about taking the filename as the project name and reference a file from the solution file? Do we need to innovative here?

a) today the project name, build and target names are only used in "generated" directory names (afaik). So changing a project name, means renaming a file and it's reference(s). What am I missing?
b) the tools could use a heuristic to immediately read the csolution file in the current directory if no solution file is specified and there is only a single solution file in the current directory

I vote for keeping it simple and in line with what users 'expect'.

**Comment by VGRSTM** [comment]
> Also I guess the same principal would be applied to clayers as well.

Yes according to my view to be applied to any csolution, cproject, clayer or cprj metadata

> How do we reference projects/layers going forward. Are we specifying the "name" the filename or both?

Is good side question to me.
-  Do we assume end user MUST setup a repository hierarchy having as top most repository csolution described then any cproject related repositories have to be children of (same if clayer vs. cproject) ? so maybe no file name / path is required
- If no reference file means we have to take care across a whole workspace end user doesn't rely on same project multiple time. Do we want such ?
- What about coming (to be confirmed) clayers delivery https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Overview.md#cmsis-pack-extensions. If done thru packs how could we prevent possible conflicts ? (guess pack name / vendor will be part of game solving issue)

Today per my trial you can write:

> solution:
  projects:
    - project: ./SWProject_1/SWProject_1.cproject.yml
      depends:
        - SWProject_2
    - project: ./../SWProject_2/SWProject_2.cproject.yml

Why the following could not fly (just an idea not claiming golden) ? In any case we are promoting explicit file system path
> solution:
  projects:
    - project: ./SWProject_1/.cproject.yml
      depends:
        - ./../SWProject_2
    - project: ./../SWProject_2/.cproject.yml

According to me *.yml file naming has to be without any hard requirements. Up to integrator to promote its own working model. You may want to promote <project name>.csolution.yml or csolution.yml or .csolution.yml (expecting here to hide a bit such metadata thinking to promote UI based flow to end user) or any other choice. Have to be open.
Then we can define some processing scheme in sync. Let's say (just an idea not claiming golden):

1. Is 'name' attribute specified as part of .yml file ? If yes such is considered. If not move to 2.
2. Is .yml file named <something>.csolution/cproject/clayer.yml ? If yes project name is <something>. If not move to 3.
3. Consider .yml file directory name as project name reference

Extra: Fact is I do not foresee why we need so much a project name. Except
- Final binary(ies) naming is project name required more ?
- Project relations if no explicit path usage

**Comment by ReinhardKeil** [comment]
For the purpose of discussion, here is the proposal: 
https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Overview.md#support-for-unnamed-yml-files

It has no additional 'name' attribute.  We can take it out of the specification, if we disagree with it.

**Comment by VGRSTM** [comment]
https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Overview.md#support-for-unnamed-yml-files

Works for me. 
Could we ensure **.***.yml is supported as well. My feeling is advanced end user may be comfortable with such metadata edition. Some others may prefer to rely on more automation like any IDE may promote.
Keep in mind such issue origin was 8.yml file naming but project name usage in general (in/out Dir, ...)

**Comment by ReinhardKeil** [comment]
When I understand you correct, you suggest that we support also ".csolution.yml'. To my knowledge files that start with '.' are invisible in a file explorer.  Is this what we want?

**Comment by jkrech** [comment]
> According to me *.yml file naming has to be without any hard requirements. Up to integrator to promote its own working model. 

I disagree here. Do we really want to differentiate at this level. Would we not want to be able to load projects developed in one environment in another environment without the need to rename files?

**Comment by VGRSTM** [comment]
My point is not to push for differentiation but to as open solution as possible as far as not too much expensive.

I'm thinking to a common processing which is looking for *csolution.yml / *cproject.yml / ... According to me no extra effort to support csolution.yml or .csolution.yml or <name>.csolution.yml ... suffix is common to all. 
At a point we may even not been asked to support such suffix. csolution file is describing in a fully explicit way related cproject file(s) and csolution executable is allowing to specify either `-s` or `-p`. But would not push for such. Sounds good to all share common suffix.

Yes could be an idea to "hide" such medata file(s) to end user according to me. As any today IDE, end user maybe able to contribute to metadata under its own responsibility helping him to sustain corner cases, automation, ... but I'm thinking good is to get some IDE services (UI, CLI) helping end user to play such .yml content.
In any case file is not fully hidden thinking git flow. But hiding from explorer reinforce according to me fact some automation metadata here.

**Comment by madchutney** [comment]
I wanted to raise some concerns I have with using file or directory name for the solution or project name.
 
- It will be more complex to implement and could be implemented differently by various tools.
  - I foresee edge cases around adding projects, renaming etc, which would impact any tools model of the project.
- This mixes domains, the project metadata will be a combination of filesystem information and information from the file itself:
  - The tools will not be able to handle a model of the solution/project defined by a schema alone.
  - The behaviour will have to be defined “out of band” to supplement the model/schema, e.g. the project name is this part of the filename if it is defined, or look up a directory to get the name etc.
  - This complicates the use of multiple software engineering techniques such as code generation and encapsulation.
- The possibility of internationalisation is being designed out, limiting the character set to that support by the file system.


I think there is a far simpler solution that will make this easier to use. If we add the solution and project name to the schemas, we have a single, easily processed, and unambiguous name for the solution or project.

**Comment by willlordarm** [comment]
If I have understood this proposal correctly solution and/or project files would not have a `name` metadata field attached to them. From an end user perspective I think this would be detrimental to usability and, specifically, findability.

In a web context metadata is important because it provides meaningful human readable (and Google indexable) content to aid discovery and selection. For example, the metadata provided in cprj-based reference designs allows the listing of example projects on keil.arm.com:

<img width="1206" alt="Screenshot 2022-02-14 at 09 19 29" src="https://user-images.githubusercontent.com/55707435/153836193-021aef29-4946-478f-a01a-f06df96e8ca7.png">

This metadata comes from this xml element in a .cprj.

```xml
<info isLayer="false">
    <name>AWS MQTT Demo</name>
    <description>Demonstrates the subscribe-publish workflow of MQTT</description>
    <category>AWS, Board, Cloud, Example, IoT, MQTT, RTOS, Socket</category>
    <license>Apache 2.0, BSD 3-Clause, MIT</license>
  </info>
```

Without the `<name>` element the project could only be listed as `aws_mqtt_demo.cprj`. This is just about human readable but only because it came from a closely controlled (and experimental) context (Lab4Layer). In reality the use of filenames would likely lead us to have project names like `BoardVendorBoard2767999_Platform_Blinky_FreeRTOS_1.0.6.csolution`. 

On the assumption that we want a system in which example software can be contributed in .csolution format I think we should mandate a `name` so that we ensure consistent metadata quality.

I would also echo Graham's concern about internationalisation. With a large part of the CMSIS market in China this should be a serious consideration.

**Comment by madchutney** [comment]
Thanks to @jkrech for questions and feedback on my counter-proposal.

> Concrete examples and consequences/differences between the two approaches

If the project name was defined inside the metadata then:

- Adv: A change to the project name would not require any filesystem changes.
- Adv: Determining the project name is very simple and treated like any other piece of metadata.
- Adv: Downloading and sharing project is more robust.
  - There is no danger of the project name changing if the filename is changed during the download or sharing process.
  - The project name will not be accidentally changed due to a containing directory name being different or the project being moved.
- DisAdv: The project name is not obvious from looking at the filesystem, the file must be read to determine the name.

> How a csolution references cproject and clayers? Is this by the name or by a relative path?

I think either would work, but if we remove the need to rename a file or directory to change the project name, then it would make sense to use a relative path as this could be treated as immutable.

However, we should be careful to check that the case of the path is correct to work across all platforms.

> Should we have a rule that the filename should match the name in the meta information.

No, I don't think so as then we would have to rename in both places.

> Concrete example of encapsulation and code generation

A common technique is to generate some code (structures / classes) from a schema to handle validation and access. If the project name is inside the document and defined by the schema, then the name is simply any other piece of data and will be automatically handled. This means the model can be easily encapsulated, reused and passed around as needed.

If the project name is not part of the document, then extra code needs to be written to handle that as a special case. This code needs to be written for every tool or system that is going to use or display the project name. They all have to be implemented in exactly the same way to get or set the name. The calculated name also has to be passed around with the rest of the model, there is no longer a simple model, but rather a model plus other data and methods.

> Is internationalization really designed out based on this decision?

No not entirely, my statement was a simplification. Portability and the likelihood of an issue arising is substantially increased by relying on the filesystem. I am not an expert in this area, but filesystems have limitations and different OSs have different limitations. For example, some file systems are case sensitive, others aren't, some retain the case but ignore it. 

Different platforms also use different encodings, the following are the standard encodings AKAIK:
- Windows: UTF16 / ANSI
- macOS: UTF8
- Linux: UTF8 (by convention)
- Web: UTF8 (by convention)

Unlike relying on the file system, we can define the encoding and character set inside the file to we can interpret the data consistently across all platforms. This would also ensure that case in preserved in any name.

**Comment by ReinhardKeil** [comment]
The idea to support unnamed `*.csolution.yml` or `*.cproject.yml` files has been dropped a while back ago.  This issue is no longer relevant. 

If we should address it again, I suggest to make a formal proposal with a complete end-to-end flow and also considers IDE.

Regarding the naming of output directories, this is different and may require another review.  See here for an proposal:
https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#output
