### ISSUE TITLE
Add schema version to csolution files / created-by + created-for 

### ISSUE THREAD

**Issue by mcgordonite** [Open-CMSIS-Pack/devtools#819]
### Problem Statement

The CMSIS ecosystem includes various tools that consume csolution files, for example CMSIS-Toolbox and VS Code extensions such as [cmsis-csolution](https://github.com/Arm-Software/vscode-cmsis-csolution/). To give a good user experience, these tools should notify the user when their csolution is written for a version of the schema that is incompatible with the tool version. This is not possible currently without using heuristics on file content, for example looking for unknown fields.

### Proposal

Add a `schema-version` property to csolution files. The details can be discussed, but as an example:
```yaml
schema-version: 1.6.0
csolution: …
```
Update the [csolution schema](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/schemas/csolution.schema.json) to include it:
```json
{
  "properties": {
    "solution": {
      "$ref": "./common.schema.json#/definitions/SolutionDescType"
    },
    "schema-version": {
      "type": "string"
    }
  },
  "required": [ "solution", "schema-version" ]
}
```
Tools could check whether this version falls within their supported range when reading a csolution file. CMSIS-Toolbox could print a warning to the command line, and VS Code extensions could show a warning notification when the schema version is unsupported. It would even be possible for tools to support multiple versions of the schema.

This pattern is already used by other tools, e.g.:
- [Node JS's package.json engines](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines). This describes what NPM versions the project works with.
- [Kubernetes pods](https://kubernetes.io/docs/concepts/workloads/pods/#using-pods). The apiVersion field is similar to the version in this proposal.
- [JSON schema](https://json-schema.org/understanding-json-schema/reference/schema.html#id4). This is more complex than a simple version, but a similar concept.

### Alternative Schema Definitions

- Require the version to match exactly. This would guarantee the user is checking their csolution against the correct schema version, but would be quite restrictive.
  ```json
  "schema-version": {
    "const": "1.6.0"
  }
  ```
- Include a list of valid versions. This guarantees the user is checking their csolution against a valid schema version, without being as restrictive as const.
  ```json
  "schema-version": {
    "enum": ["1.5.0", "1.6.0"]
  }
  ```

### Versioning

The version number could match the CMSIS-Toolbox version, but it might be better to introduce an independent version number for the schema. Using semantic versioning would help tools to maintain their version range.

**Comment by ReinhardKeil** [comment]
@mcgordonite we csolution 2.0 we indent only to make upward compatible changes. By applying a schema check, a syntax problem with a csolution.yml file could be identify.  What is then the real benefit of requesting a schema-version in yml files?

**Comment by mcgordonite** [comment]
I think we need to distinguish between forwards and backwards compatibility here. For example, say we want to add a new feature to the [`processor`](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#processor) node in future:

```yaml
project:
  processor:
    trustzone: secure
    new_feature: enabled
```

This is a backwards compatible change: a csolution written for the old schema is compatible with the new one. However, it is not forwards compatible: an old version of cbuild cannot build a csolution file that enables the new feature.

**Comment by ReinhardKeil** [comment]
An alternative proposal is to specify the tool that has been used when creating the example, i.e.

```
 ctools: csolution@1.5
```

**Comment by fred-r** [comment]
Cab be a bit more complex, because you create a project with one version of a tool but we do not know which features supported by this tool have been used or not.

So:
1. you check the reference version ==> you already know if you have a chance to support the project or clearly not (semantic versioning)
2. you check the features in use by analyzing the content of the project
3. you check this list of "features in use" versus the list of supported features of your own tool

**Comment by mcgordonite** [comment]
Some points from the Technical Project Meeting yesterday:
- The version of the schema itself might not be sufficient. There are additional rules (e.g.: access sequences) that cannot be encoded in the JSON schema.
- Separating the format version from the tool version was considered important, since some partners may provide their own tools that interpret csolutions.
- Partners may want to track which tool generated the csolution.

This suggests we want to store the version of the _format_ or the _specification_ rather than the schema or the tool. Additionally, we could track metadata about which tool generated the file, but I think that should be raised as a separate issue.

```yaml
spec-version: 1.5
solution: <solution description>
```

Then tools would basically follow the process outlined by @fred-r in https://github.com/Open-CMSIS-Pack/devtools/issues/819#issuecomment-1503504013:
1. Check if the spec version is known by the tool. If it isn't, it can't know what features are unsupported. For example, we can't know to look for new file types. This check could use semver. For example, if the tool understands version 1.5.0 and the csolution uses spec 1.5.3, it can assume there are no new file types.
2. Check for unsupported features. For example, if the tool doesn't support layers, it can check for the layers node in cproject files.

**Comment by fred-r** [comment]
Yes, and with semver you could also save some time for step 2:
- if you support revision 1.5.0 of the spec "fully" (all features)
- and if only the .patch has been updated, then there is no new feature, so you know you can use this file

If you support only a subset of 1.5.0, then you need to do the analysis.

Alternate solution: define "interoperability profiles"
For instance:
* 1.5.0-full: full profile by default (all features)
* 1.5.0-core: only the "core" features so no advanced features like the "clayer support"

**Comment by mcgordonite** [comment]
Yes, I think the Csolution extension could use `created-for` to check compatibility by extracting the version from `ctools@1.5.0`.

It might not work so well when the solution is `created-for` a different tool, e.g. `other-tool@2.3.1`, since we won't know what specification version 2.3.1 of that tool uses.

**Comment by ReinhardKeil** [comment]
I know you can only handle tools that are known.

**Comment by fred-r** [comment]
Dear all,

first of all I apologize in advance for this very long (and very boring) contribution.
I think the point being discussed in this thread is wider than just a matter of schema versioning.

**1. "Philosophy"**

This Open-CMSIS-Pack project is defined like this:
[The Open-CMSIS-Pack project offers a flexible and easy to use end to end development flow for embedded software - from project creation to software execution on real or virtual hardware.](https://github.com/Open-CMSIS-Pack#about-open-cmsis-pack)

So, to me, it is not only about software packaging and delivery (CMSIS-Pack), but also project management (csolution).

To day, the first point is covered by a spec: [Open-CMSIS-Pack-Spec](https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec).
But, the latter point is covered "only" by a reference tool: [csolution](https://github.com/Open-CMSIS-Pack/devtools/tree/main/tools/projmgr)

I think this raises issues because a tool is not a specification.
So, today, we can't really handle the interoperability at project management level, we can do this only at CMSIS-pack level.

I agree that the tool is managed by its contributors and I assume the maintainer is @brondani, I do not challenge this.
But, if the project management is part of the Open-CMSIS initiative then I think a spec is needed, so that we can know if a tool complies to it or not (just like for the CMSIS-Packs).

Today, I think having only the vanilla/reference tool is probably fine for ARM but I am not sure it is sufficient for the other partners in this initiative (@iomint to provide his point of view here).

**2. Proposal to allow interoperability at project management level**
I would like that we create a real specification of the project manager tool.
The basis for this could be this (user manual)[https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Overview.md].
This spec should be versioned.

**3. Consequence for the initial issue discussed here**
If we have a spec, then I think we can do 2 things.

On tools side (can be the vanilla tool or any other tool implementing the spec), we can indicate what we support.
On project sides, we can add an information about the spec features we use.

This would be more precise than ```created-by``` and ```created-for```.

**4. Proposal**

I suggest having a field like this:
- "in the tool" to define its capabilities
- in the project YML file(s) to define the capabilities it requires

So, to be more specific a tool from ARM could define this:
```
capabilities:
  core-spec-version:
    revision: 1.5.0
    optional_features:
      feat_clayer:
        description: clayer concept
        supported: true
      feat_hwproject:
        description: hw project concept
        supported: false
```

and a tool from ST could define this:
```
capabilities:
  core-spec-version:
    revision: 1.5.0
    optional_features:
      feat_clayer:
        description: clayer concept
        supported: false
      feat_hwproject:
        description: hw project concept
        supported: true
```

Then, a project would indicate what it requires:
```
required_capabilities:
  core-spec-version:
    revision: 1.5.0
    optional_features:
      feat_clayer:
        description: clayer concept
        required: false
      feat_hwproject:
        description: hw project concept
        required: true
```

So, the interoperability would become predictable:

```
if (project.required_capabilities == tool.capabilities) then
    the project can be managed by the tool
else
    vendor specific implementation depending on what is missing
endif
```

@jkrech and @ReinhardKeil, I know you are not in favor of going in this direction, but it is the way I see to ensure interoperability at project level.

**Comment by mcgordonite** [comment]
> So, to me, it is not only about software packaging and delivery (CMSIS-Pack), but also project management (csolution).
To day, the first point is covered by a spec: [Open-CMSIS-Pack-Spec](https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec).
But, the latter point is covered "only" by a reference tool: [csolution](https://github.com/Open-CMSIS-Pack/devtools/tree/main/tools/projmgr)

@fred-r I think the [manual](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Overview.md) is doing the job of the specification for project management.

**Comment by fred-r** [comment]
Hi @mcgordonite  and all,

one again I apologize in advance for probably complexifying things...
But, I agree that the manual is more or less the spec.

My point is not only about the content, but more about the doc status and management.
To me, to become a specification handled by this working group, it should have its own placeholder here:
[https://github.com/Open-CMSIS-Pack#specifications](https://github.com/Open-CMSIS-Pack#specifications)

At the moment it is a user manual, and to me a user manual is dedicated to one specific implementation while a specification describes a set of requirements, principles and mechanisms that can be implemented in various manners.

So, as long as we have only a user manual then I think there is no possibility to talk about interoperability, because a user manual describes 1 tool so 1 implementation.

My point is more to say that:
1. the project management is probably part of the wharter of this working group
2. the project management requires a spec
3. anybody could decide to implement this spec or not

So, here the schema version and in the end the interoperability would make sense.
This would be the required cradle to define features, capabilities and what is optional or not to be interoperable.

On another aspect, I also think that today we are in a chicken and egg situation.
Only ARM is contributing to the project management documentation...but this is because this documentation is a user manual describing ARM's implementation.

If you want (more) contributions, then a spec is needed.
As you can see in the Open-CMSIS-Pack spec, there has been contributions from ST for instance.

These were my 2 cents, I let @iomint and my other colleagues -@slhultgren, @mdortelstm - comment further if needed (and maybe disagree)

**Comment by ReinhardKeil** [comment]
**For examples, I recommend not to add:**
```
# yaml-language-server: $schema=https://raw.githubusercontent.com/Open-CMSIS-Pack/devtools/schemas/projmgr/1.6.0/tools/projmgr/schemas/csolution.schema.json
```
VS Code picks-up the YML schema of the CMSIS-Toolbox that is installed; users may utilize new features that may be added over time to CMSIS-Toolbox when working on such projects.

**Instead add:**
```
` created-for: ctools@1.6`
```
to indicate that an example is created with the feature set of CMSIS-Toolbox 1.6.

**Comment by ReinhardKeil** [comment]
I think we have concluded on this one.

*** Please raise a new issue an describe the problem that you want to solve ***
