### ISSUE TITLE
[devtools] Promote standalone tools being orchestrated by consumer itself

### ISSUE THREAD

**Issue by VGRSTM** [Open-CMSIS-Pack/devtools#85]
Currently Open-CMSIS devtools are supporting lot of nice features but would require some refactoring allowing to promote required flexibility to enable wide adoption. I would push to get "atomic" features a consumer may invoke at proper time according its own workflow.

I would appreciate to get following "atomic" features:

- [cpackget] is fine to me. Its scope / feature list is quite well defined. Maybe to be renamed to [packget] compared to x2 following items.

- [packgen] is fine to me. Its scope / feature list is quite well defined.

- [packchk] is fine to me. Its scope / feature list is quite well defined.

- I foresee following current [projmgr] capabilities as having to be part of a dedicated new [packlist] tool ?
`Commands:`
`  list packs          Print list of installed packs`
`       devices        Print list of available device names`
`       components     Print list of available components`

- [buildmgr] has to be restricted in my view to generation from .cprj / .clayer to <ProjectFile>.mak / CMakeLists.txt leading to a [buildgen] tool ? Today [buildmgr] is involved doing *.clayer composition to .cprj and generating RTE material.
Sounds *.clayer composition is moving to [projmgr] now.
About RTE I'm myself confused "source code" generation is done asking for *.mak / CMakeLists.txt creation ... not able to foresee relationship between both.

- [projmgr] has to be restricted in my view to generation from csolution.yml / cproject.yml / clayer.yml to .cprj leading to a [projgen] tool ? (already multiple comments if https://github.com/Open-CMSIS-Pack/devtools/pull/77/files 'project manager' is maybe not best naming)

- We need then some [codegen] tool I guess to sustain code generation related to configurable components. Today such process is only available if Keil uVision usage (thru .gpdsc  usage). According to me [codegen] has to be independent of [projmgr] process because end user may revisit some component parameters which are leading to same file set (content update "only") what has no impact on *.yml/*.cprj files.

- We need some [rtegen] tool I guess to get such RTE process explicit out of any other process.

Based on all such a vendor may be able to rely on Open-CMSIS common assets keeping some room to support its own workflow I'm thinking.

**Comment by jkrech** [comment]
Listing the installed packs is planned to be part of cpackget
Assuming that there is local packs, pack version selectors, etc. specified in the context of the workspace/solution the projmgr would list those pack versions "active" in the scope of the workspace/solution
The same is true for listing devices. projmgr will list only the devices "visible" in the context.
Components shall be listed based on the filter attributes set by the project context, e.g. selected device (processor, processor feature used e.g. FPU), secure vs. non-secure context and even toolchain.
Due to the context sensitivity this is handled by projmgr and not independently.

Once a new component is selected there are a couple of things that need to happen
a) check dependencies specified by new component and ask the user to resolve or automatically resolve if no choices.
b) add configuration files to the project <RTE> folder, if not present. User can edit config files now or later
c) run generator(s) - interactively or based on configuration file input and component selection 
d) optionally allow arbitrary re-execution of generator(s) 
We need to investigate where we hook in the resource management but ultimately it is configuration + generator as well. The tricky bit is how different generators impact each other and therefore we may need to re-run them.

Regarding cbuildgen we are in agreement that it will only generate the build configurations in CMakelist.txt 
- no management of layers
- no changes to files

I don't think that codegen or rtegen tools are needed as separate tools but happy to be told otherwise.

**Comment by VGRSTM** [comment]
@jkrech, Thanks for comments.

1) > Due to the context sensitivity this is handled by projmgr

I got it now ! Project manager addon if pack, component, device, ... listing is csolution.yml context aware. I was missing that. I was bad according my trial based on current [projmgr] binary behavior. At that time `./projmgr list components` is reporting me all components available on my local host.
Anyway I agree context aware features but still would not be good to get it supported by [cpackget] then ? sounds like a subset of [cpackget] capabilities adding filters on top of search request (`-s <csolution.yml>` support addon ?).

2) > Once a new component is selected there are a couple of things that need to happen

I fully agree. Still thinking then things to happen have to be available in an atomic way to vendor integrating such solutions.
I'm not fan about a magic button handling all at once without any way to rearrange action sequence or ...
As stated by you there are many places end user action may be required. Cannot rely so on a monolithic process.

Selecting a new component may requires to resolve some dependencies. I would my self prefer to do such at component selection step. 
Selecting a new component, having done proper resolution end user may have some interest to get related generated code without any aim to deal at what time with build concerns ... why running then a [projmgr] process ending with cprj stuff ?

3) >I don't think that codegen or rtegen tools are needed as separate tools but happy to be told otherwise.

I tend to agree. Promoting two tools was still in the way to promote as much as flexibility as possible to such tools consumer. Possibly both will be run in sequence in all case but who knows.

**Comment by jkrech** [comment]
Maybe I am overly optimistic but my goal is a well defined flow that works for everyone even if not all steps are always used/executed. Commonality is key for this project to ensure wide adoption.

**Comment by VGRSTM** [comment]
> Commonality is key for this project to ensure wide adoption.

I'm fully in sync. but would reinforce to my view that commonality is relying on underlying metadata sustaining workflows. Metadata within Open-CMSIS context are *.yml, *.pdsc, *.pack, *.cprj, *.*zone, ....
In addition to, obviously, related schema availability is key ensuring deployment / robustness.

Workflow proposals and first guess tools sustaining them are good too as at least helps to define & demonstrate promoted metadatas are flying if real life but sounds to me like nice to have in comparison. Such said tools if existing are obviously welcome added value if scalable / flexible enough supporting faster integration / deployment.

**Comment by ReinhardKeil** [comment]
@VGRSTM could you review and list what is really open and important.  I guess a lot has been addressed indirectly by the progress that these tools have made since your initial report.

**Comment by ReinhardKeil** [comment]
closing this issue as there is no further feedback.  Please raise separate tickets if you feel that we should address an aspect.
