### ISSUE TITLE
[cbuildgen] regression with 1.6.0: gpdsc file ignored

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#860]
Used version: CMSIS-Toolbox Version 1.6.0

I have one project defined like this:
```
`-- STM32_HAL_Driver_codegen.gpdsc
`-- hal_gpio_exti.cproject.yml
`-- hal_gpio_exti.csolution.yml
```

With previous cbuild tool, I could build it,
now it seeems that gpdsc is not taken into account

**Comment by jkrech** [comment]
Could you please provide a bit more context.
When you write you have a project you mean you have a

hal_gpio_exti.csolution.yml file referencing the cproject:
```
  projects:
  - project: ./hal_gpio_exti.cproject.yml 
```

In the cproject you reference a component that has a generator attribute in a pack that has a generator description.

If you run `csolution list generators` and `csolution list dependencies` specifying the context. What is the output?

Thanks a lot for helping us to reproduce your problem.

**Comment by jkrech** [comment]
@jeromecoutant, the build should work again in CMSIS-Toolbox 1.7.0 .
In the README of the repository you are mentioning a separate problem which is an incorrect filename of the generator "project" argument in the cbuild.yml file for the context.
Could you please raise a separate issue for that, since this is not related and is not a recent regression.
@slhultgren, maybe this is something you want to look into, as I think this could have been in the area of your PR.
