### ISSUE TITLE
Implement `generator-dir:` and $GeneratorId$

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#880]
To complete support for generators, implement:
- [`generator-dir:`](https://github.com/open-cmsis-pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#generator-dir)
- [`$GeneratorId$`](https://github.com/open-cmsis-pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#access-sequences)

**Comment by slhultgren** [comment]
@ReinhardKeil This proposal looks good to me, just some minor comments as always :)

* `clevel.yml` mentioned in the docs is probably a typo for `clayer.yml`?
* The priority order for the `generator-dir` in should probably be? 
  1. `cproject.yml`, if not specified, read from
  2. `csolution.yml`, if not specified, read from
  3. `clayer.yml`

**Comment by brondani** [comment]
@ReinhardKeil 
1. The `$GeneratorId$` as access sequence sounds uncommon because it is not related to the solution nor to a specific context.
The [example](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md?plain=1#L715) seems to describe the default case. Are there other use cases where this "access sequence" would be needed? Otherwise I would recommend to avoid it.

2. In addition to the introduction of `generator-dir`, I believe we should also consider taking `rtedir` out of `output-dirs`. Maybe `generator-dir` and `rte-dir` could be part of a new node?

**Comment by jkrech** [comment]
see cmsis-toolbox 2.0.0-dev0
