### ISSUE TITLE
Can't link my code, file not found when using absolute path

### ISSUE THREAD

**Issue by jankap** [Open-CMSIS-Pack/devtools#984]
**Describe the bug**
The linking step fails due to absolute paths in `armclang` call:

```
./ArmCompilerforEmbedded6.20.1/bin/armclang -E --target=arm-arm-none-eabi -mcpu=Cortex-M3 -mfpu=none -xc -include /workspaces/prj/RTE/Device/STM32F103TB/regions_STM32F103TB.h /home/dev/cmsis-toolbox-linux-amd64/etc/ac6_linker_script.sct -o /workspaces/build/tmp/debug/ac6_linker_script.sct.pp 
```

Results in 

> <built-in>:1:10: fatal error: '/workspaces/prj/RTE/Device/STM32F103TB/regions_STM32F103TB.h' file not found
> #include "/workspaces/prj/RTE/Device/STM32F103TB/regions_STM32F103TB.h"
>          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.

It works well with cding into the path:

```
cd /workspaces/prj &&
./ArmCompilerforEmbedded6.20.1/bin/armclang -E --target=arm-arm-none-eabi -mcpu=Cortex-M3 -mfpu=none -xc -include prj/RTE/Device/STM32F103TB/regions_STM32F103TB.h /home/dev/cmsis-toolbox-linux-amd64/etc/ac6_linker_script.sct -o /workspaces/build/tmp/debug/ac6_linker_script.sct.pp 
```

The `ac6_linker_script.sct.pp` file is created sucessfully.

**Environment (please complete the following information):**

- CMSIS-Toolbox
- v1.7.0
- OS: Ubuntu 22.04

**Additional context**
Same behavior with AC6@8.20.1

In AC6.6.18.0.cmake, this line configures the call: `set(CPP_ARGS_LD_SCRIPT "${CPP_FLAGS} ${CPP_DEFINES} -include \"${LD_REGIONS}\" \"${LD_SCRIPT}\" -o \"${LD_SCRIPT_PP}\"")` but I don't understand where `${LD_SCRIPT}` comes from and why it's a full path.

Is this an issue with CMSIS-toolbox or AC6?
Any help is appreciated, I'm stuck in the middle of a migration which takes way too long already.

Thanks.

**Comment by brondani** [comment]
Hi @jankap, first of all I would recommend to use the latest cmsis-toolbox [2.0.0-dev1](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/releases/tag/2.0.0-dev1).

Anyway I tried with the cmsis-toolbox 1.7.0 and AC6 6.20.1 in Linux and in Windows and it works with absolute paths in both cases. You can inspect the generated CMakeLists.txt where you should always find absolute paths.

Something that I have observed in your comment is that you do a `cd /workspaces/prj` and then the preprocessor includes a relative file `-include prj/RTE/...` that would result in `/workspaces/prj/prj/RTE/...` - note the double `prj`, it does not match the absolute path mentioned in the first call.

Would you be able to provide the full project in order to reproduce the issue you are facing? Thanks!

**Comment by ReinhardKeil** [comment]
We cannot duplicate this issue. Please help us to understand the problem otherwise we will close it.

**Comment by jankap** [comment]
I can't reproduce the issue either. Very strange, but it had nothing to do
with it the typo above.

Can be closed, sorry for the inconvenience.
